const AUTHENTICATE_ROUTE = {
  SIGN_IN: '@AUTHENTICATE_ROUTE/SIGN_IN',
  SIGN_UP: '@AUTHENTICATE_ROUTE/SIGN_UP',
};

const APP_ROUTE = {
  MAIN_TAB: 'MAIN_TAB',
};

export {AUTHENTICATE_ROUTE, APP_ROUTE};
